### ISSUE TITLE
Erstellen von Tests für das Statistikmodul

### ISSUE THREAD

**Issue by wulffant** [highmed/SmICSCore#33]
to be discussed with @biermapa

**Comment by yussefal** [comment]
**Stand:**  Erste Tests für Statistikmodul sind fertig. 
**TODO:** Ersten Code Review mit @biermapa und dann weiter testen.

**Comment by yussefal** [comment]
**Stand**: Ersten Code Review mit @biermapa durchgeführt.
**TODO**:    
- [x] Testprojekt auf dem Server neue anlegen
- [x] Teststruktur anpassen 
- [x] Den ersten Teil erweitern und dann mergen
- [x] Tests für den zweiten Teil  schreiben.

**Comment by yussefal** [comment]
Es fehlen noch Tests für Symptome und dann kann ein Code Review von @biermapa durchgeführt werden.

**Comment by yussefal** [comment]
Tests für Symptome hinzugefügrt und Code Review mit @biermapa und @Kuri99 durchgeführt. Somit 

Die Tests können jetzt in Devlope gemerged werden!

**Comment by yussefal** [comment]
Die Tests sind in cosurv_develop gemerged worden
